package primero;
// Generated 23-dic-2018 14:43:26 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Feria generated by hbm2java
 */
@Entity
@Table(name="feria")
public class Feria implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	
	@Column(name = "id_feria", unique = true, nullable = false)
	private Integer idFeria;
	
	@Column(name = "nombre", length = 50)
	private String nombre;
	
	@Column(name = "superficie_feria")
	private Integer superficieFeria;
	private Set<Object> stands = new HashSet<Object>(0);

	public Feria() {
	}

	public Feria(String nombre, Integer superficieFeria, Set<Object> stands) {
		this.nombre = nombre;
		this.superficieFeria = superficieFeria;
		this.stands = stands;
	}


	
	public Integer getIdFeria() {
		return this.idFeria;
	}

	public void setIdFeria(Integer idFeria) {
		this.idFeria = idFeria;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getSuperficieFeria() {
		return this.superficieFeria;
	}

	public void setSuperficieFeria(Integer superficieFeria) {
		this.superficieFeria = superficieFeria;
	}

	public Set<Object> getStands() {
		return this.stands;
	}

	public void setStands(Set<Object> stands) {
		this.stands = stands;
	}

}
