package primero;
// Generated 23-dic-2018 14:43:26 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Modular generated by hbm2java
 */
@Entity
@Table(name="modular")
public class Modular implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	
	@Column(name = "id_modular", unique = true, nullable = false)
	private Integer idModular;
	private Stand stand;
	
	@Column(name = "numero_modulos")
	private Integer numeroModulos;
	
	@Column(name = "tipo_stand")
	private String tipoStand;

	public Modular() {
	}

	public Modular(Stand stand) {
		this.stand = stand;
	}

	public Modular(Stand stand, Integer numeroModulos, String tipoStand) {
		this.stand = stand;
		this.numeroModulos = numeroModulos;
		this.tipoStand = tipoStand;
	}

	public Integer getIdModular() {
		return this.idModular;
	}

	public void setIdModular(Integer idModular) {
		this.idModular = idModular;
	}

	public Stand getStand() {
		return this.stand;
	}

	public void setStand(Stand stand) {
		this.stand = stand;
	}

	public Integer getNumeroModulos() {
		return this.numeroModulos;
	}

	public void setNumeroModulos(Integer numeroModulos) {
		this.numeroModulos = numeroModulos;
	}

	public String getTipoStand() {
		return this.tipoStand;
	}

	public void setTipoStand(String tipoStand) {
		this.tipoStand = tipoStand;
	}

}
