package primero;
// Generated 23-dic-2018 14:43:26 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;

/**
 * Personalizado generated by hbm2java
 */
@DynamicUpdate
@Table(name="personalizado")
public class Personalizado implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	
	@Column(name = "id_personalizado", unique = true, nullable = false)
	private Integer idPersonalizado;
	private Stand stand;
	
	@Column(name = "caracteristicas")
	private String caracteristicas;
	
	@Column(name = "tipo_stand")
	private String tipoStand;

	public Personalizado() {
	}

	public Personalizado(Stand stand) {
		this.stand = stand;
	}

	public Personalizado(Stand stand, String caracteristicas, String tipoStand) {
		this.stand = stand;
		this.caracteristicas = caracteristicas;
		this.tipoStand = tipoStand;
	}

	public Integer getIdPersonalizado() {
		return this.idPersonalizado;
	}

	public void setIdPersonalizado(Integer idPersonalizado) {
		this.idPersonalizado = idPersonalizado;
	}

	public Stand getStand() {
		return this.stand;
	}

	public void setStand(Stand stand) {
		this.stand = stand;
	}

	public String getCaracteristicas() {
		return this.caracteristicas;
	}

	public void setCaracteristicas(String caracteristicas) {
		this.caracteristicas = caracteristicas;
	}

	public String getTipoStand() {
		return this.tipoStand;
	}

	public void setTipoStand(String tipoStand) {
		this.tipoStand = tipoStand;
	}

}
